### ISSUE TITLE
React kanban board setup

### ISSUE THREAD

**Issue by Nasirkhan294** [Nasirkhan294/space-traverler-hub#25]
### Requirements for the project setup

- [ ] Project kanban board [click here](https://github.com/Nasirkhan294/space-traverler-hub/projects/1)
- [ ] We are two team members for this project: Nasir & Sumeya

**Comment by osamaashraf6** [comment]
Hi @Nasirkhan294 😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![MinionsGIF (2)](https://github.com/chudisoft/Portfolio-Microverse/assets/83360636/03538ef5-c2f7-4fd5-ab18-e5dba7d7309e)

## Highlights🎉 🎉 


- [ ] Set up the Kanban board correctly.✔️
- [ ] Mention the number of students ✔️
- [ ]  Project tasks evenly distributed.✔️

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nasirkhan294** [comment]
Hi @osamaashraf6, Thanks for the approval!
